### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by mochaaaa11** [FN-FAL113/cs2-server-picker#14]
whether i block 2 servers or all the ones i dont want my "best ping is 70ms" idk what it is with csgo dedi servers but always connects me to 60+ servers despite many servers having a better ping for me. its the only game that does this. at some point on csgo i managed to fix it somehow and was gettin into servers with 17-30ms but 99% of the time it says my best ping to official servers is 70ms and cant connect to any lower. frustrating cause in community servers i get as low as 12ms, some cs servers show pings from 17-50ms, valorant i get 23ms, all other games my ping is 17-40ms. but csgo just wont let me connect to my side of the region

**Comment by FN-FAL113** [comment]
> whether i block 2 servers or all the ones i dont want my "best ping is 70ms" idk what it is with csgo dedi servers but always connects me to 60+ servers despite many servers having a better ping for me. its the only game that does this. at some point on csgo i managed to fix it somehow and was gettin into servers with 17-30ms but 99% of the time it says my best ping to official servers is 70ms and cant connect to any lower. frustrating cause in community servers i get as low as 12ms, some cs servers show pings from 17-50ms, valorant i get 23ms, all other games my ping is 17-40ms. but csgo just wont let me connect to my side of the region

Please try to refer to the console output check the server you are being relayed to as mentioned in (#4):
https://github.com/FN-FAL113/cs2-server-picker#faq

**Comment by mochaaaa11** [comment]
when i put stauts in console, it does not show any server info like in csgo.

**Comment by FN-FAL113** [comment]
> i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)

prolly you are being relayed to different server (nearest, available, etc...)

**Comment by mochaaaa11** [comment]
> > i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)
> 
> prolly you are being relayed to different server (nearest, available, etc...)

is there a reason why cs specifically only connects me to high ping servers? if i do a ping test online or even in your tool, i see many servers with lower pings and like i said, it had fixed months ago where i was getting into low ping lobbies but idk why it doesnt this only for this game, i have a good fiber connection, A+ bufferbloat. idk

**Comment by FN-FAL113** [comment]
> > > i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)
> > 
> > 
> > prolly you are being relayed to different server (nearest, available, etc...)
> 
> is there a reason why cs specifically only connects me to high ping servers? if i do a ping test online or even in your tool, i see many servers with lower pings and like i said, it had fixed months ago where i was getting into low ping lobbies but idk why it does this only for this game, i have a good fiber connection, A+ bufferbloat. idk

have you tested the server picker to block low ping locations and only select high ping then join them to see if the ping is high, this is to see if servers are properly blocked.

**Comment by FN-FAL113** [comment]
iirc community servers connect you to its dedicated server while if you try to join official ones, cs routes you to some servers for some reasons which are not explicitly stated in the console, etc.

**Comment by mochaaaa11** [comment]
> iirc community servers connect you to its dedicated server while if you try to join official ones, cs routes you to some servers for some reasons which are not explicitly stated in the console, etc.

still the same

**Comment by mochaaaa11** [comment]
> > > > i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)
> > > 
> > > 
> > > prolly you are being relayed to different server (nearest, available, etc...)
> > 
> > 
> > is there a reason why cs specifically only connects me to high ping servers? if i do a ping test online or even in your tool, i see many servers with lower pings and like i said, it had fixed months ago where i was getting into low ping lobbies but idk why it does this only for this game, i have a good fiber connection, A+ bufferbloat. idk
> 
> have you tested the server picker to block low ping locations and only select high ping then join them to see if the ping is high, this is to see if servers are properly blocked.

still the samethng

**Comment by FN-FAL113** [comment]
> > > > > i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)
> > > > 
> > > > 
> > > > prolly you are being relayed to different server (nearest, available, etc...)
> > > 
> > > 
> > > is there a reason why cs specifically only connects me to high ping servers? if i do a ping test online or even in your tool, i see many servers with lower pings and like i said, it had fixed months ago where i was getting into low ping lobbies but idk why it does this only for this game, i have a good fiber connection, A+ bufferbloat. idk
> > 
> > 
> > have you tested the server picker to block low ping locations and only select high ping then join them to see if the ping is high, this is to see if servers are properly blocked.
> 
> still the samethng

prolly cs2 relaying you to different server that is available

**Comment by mochaaaa11** [comment]
> > > > > > i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)
> > > > > 
> > > > > 
> > > > > prolly you are being relayed to different server (nearest, available, etc...)
> > > > 
> > > > 
> > > > is there a reason why cs specifically only connects me to high ping servers? if i do a ping test online or even in your tool, i see many servers with lower pings and like i said, it had fixed months ago where i was getting into low ping lobbies but idk why it does this only for this game, i have a good fiber connection, A+ bufferbloat. idk
> > > 
> > > 
> > > have you tested the server picker to block low ping locations and only select high ping then join them to see if the ping is high, this is to see if servers are properly blocked.
> > 
> > 
> > still the samethng
> 
> prolly cs2 relaying you to different server that is available

what would be the reason for this if i have better ping on other servers and its worked at some point in the past?

**Comment by FN-FAL113** [comment]
> > > > > > > i put status in console, it does not show any server info like in csgo. it was also like this before i tried this tool. never showed server IP or region like in normal csgo. ![Screenshot (15)](https://user-images.githubusercontent.com/143021305/271804911-fb93a0c6-a525-41d8-a3a7-0e7f9479f35b.png)
> > > > > > 
> > > > > > 
> > > > > > prolly you are being relayed to different server (nearest, available, etc...)
> > > > > 
> > > > > 
> > > > > is there a reason why cs specifically only connects me to high ping servers? if i do a ping test online or even in your tool, i see many servers with lower pings and like i said, it had fixed months ago where i was getting into low ping lobbies but idk why it does this only for this game, i have a good fiber connection, A+ bufferbloat. idk
> > > > 
> > > > 
> > > > have you tested the server picker to block low ping locations and only select high ping then join them to see if the ping is high, this is to see if servers are properly blocked.
> > > 
> > > 
> > > still the samethng
> > 
> > 
> > prolly cs2 relaying you to different server that is available
> 
> what would be the reason for this if i have better ping on other servers and its worked at some point in the past?

idk if the settings for changing max ping for finding servers in-game still exist, check it out also

**Comment by mochaaaa11** [comment]
would there be a way you could send me all the ips of the servers in your tool that way i can try to block in firewall?

**Comment by FN-FAL113** [comment]
> would there be a way you could send me all the ips of the servers in your tool that way i can try to block in firewall?

https://[api.steampowered.com/ISteamApps/GetSDRConfig/v1/?appid=730](https://api.steampowered.com/ISteamApps/GetSDRConfig/v1/?appid=730)

here it is, hit me up here, try also blocking the tcp protocol, my tool only blocks UDP protocol

**Comment by mochaaaa11** [comment]
okay so thats weird, still getting same results even blocking in firewall

**Comment by FN-FAL113** [comment]
> okay so thats weird, still getting same results even blocking in firewall

Thats unfortunate, you location can be factor and since cs2 is an upgraded version of cs:go, its networking was revamped for sure.
