### ISSUE TITLE
Request: option "use hosts file for ip blocking"

### ISSUE THREAD

**Issue by rainbowjose** [FN-FAL113/cs2-server-picker#16]
Hi. I don't know what mechanism is used now to block IP, I assume it's firewall mechanisms. But many people disable firewall and many other windows mechanisms, so these methods may not work. I suggest adding blocking options through C:/Windows/System32/drivers/etc/hosts.

**Comment by rainbowjose** [comment]
And add "donate" button :D

**Comment by FN-FAL113** [comment]
> Hi. I don't know what mechanism is used now to block IP, I assume it's firewall mechanisms. But many people disable firewall and many other windows mechanisms, so these methods may not work. I suggest adding blocking options through C:/Windows/System32/drivers/etc/hosts.

Will test this out! Thank you for the feedback. Will get back here with any progress hopefully its viable with vb.net.

**Comment by FN-FAL113** [comment]
> And add "donate" button :D

Will do! Thank you

**Comment by FN-FAL113** [comment]
> Hi. I don't know what mechanism is used now to block IP, I assume it's firewall mechanisms. But many people disable firewall and many other windows mechanisms, so these methods may not work. I suggest adding blocking options through C:/Windows/System32/drivers/etc/hosts.

Hi unfortunately, upon my research Windows Host files are used for domain names, before the client try to access a domain/website, windows checks the host file for entries that are being resolved through a dns server. Since cs2 servers are using ip addresses already it is not applicable to use host files.

**Comment by FN-FAL113** [comment]
Will do another research since host files are limited to domain names only.

**Comment by rainbowjose** [comment]
Sad! Thank you.

**Comment by FN-FAL113** [comment]
> Sad! Thank you.

Will try my best still, I'm not sure if you can still receive notifications from replies on this the previous issue case but I mentioned some stuffs there if you have time to check regarding the donation you've made :):
https://github.com/FN-FAL113/cs2-server-picker/issues/15
