### ISSUE TITLE
an Error has occurred while retrieving server data! please report to github issue-tracker

### ISSUE THREAD

**Issue by iDarkGamer** [FN-FAL113/cs2-server-picker#18]
i have this problem from morning. what should i do?

**Comment by FN-FAL113** [comment]
Will check this later, midnight currently in my timezone

**Comment by FN-FAL113** [comment]
> i have this problem from morning. what should i do?

Can you please provide more context:
```
Operating System: 
Third-party antivirus software: (leave blank if windows defender only)
Firewall enabled: (true or false)
```

**Comment by iDarkGamer** [comment]
windows 10 64bit
Bitdefender Antivirus
BitDefender Firewall is on

**Comment by FN-FAL113** [comment]
> windows 10 64bit Bitdefender Antivirus BitDefender Firewall is on

Have you tested it out without bitdefender firewall enabled, this app utilizes windows firewall and there also may be a chance that your av and ita firewall is blocking the app from fetching server data on valve rest api's

**Comment by iDarkGamer** [comment]
Still the same issue.
but i turned on my vpn and i got that server update but when i turned it off again. its not working anymore

**Comment by FN-FAL113** [comment]
> Still the same issue. but i turned on my vpn and i got that server update but when i turned it off again. its not working anymore

I'm suspecting it may be your isp, I'd test fully uninstalling bitdefender with pc restart and utilize windows defender to manage the firewall. Might be a hassle on your side but pretty sure its a problem on your network or system configuration.

**Comment by iDarkGamer** [comment]
i guess its because im in iran and they set a sanction against us :\
but other server pickers are ok and steam is ok too i dont know what is it about

**Comment by FN-FAL113** [comment]
> i guess its because im in iran and they set a sanction against us : but other server pickers are ok and steam is ok too i dont know what is it about

Could be since you mentioned using a vpn made it work and able to fetch data

**Comment by iDarkGamer** [comment]
anyway, thanks for you helps. i will tell you the reason if i can fix it in future

**Comment by FN-FAL113** [comment]
Hit me up here anytime, I will close this issue but feel free to reply back even if its closed

**Comment by FN-FAL113** [comment]
To follow up you may use the vpn to make the app work instead, nothing wrong with it and you can block servers and turn off the vpn. You may do this everytime u wanna make changes like blocking or unblocking.

**Comment by JohnNielse** [comment]
![Screenshot 2023-10-18 092140](https://github.com/FN-FAL113/cs2-server-picker/assets/20168314/4eda46ab-2905-4ab4-8f8f-6b25811a87f6)
Same thing is happening with Windows Defender,

**Comment by FN-FAL113** [comment]
> ![Screenshot 2023-10-18 092140](https://user-images.githubusercontent.com/20168314/276141356-4eda46ab-2905-4ab4-8f8f-6b25811a87f6.png) Same thing is happening with Windows Defender,

its false positive, you may unblock the app from windows defender. As mentioned in the readme faq its costs a lot of money to sign an application with known publisher.
