### ISSUE TITLE
This thing is not working at all

### ISSUE THREAD

**Issue by NewbieCPlusPlus** [FN-FAL113/cs2-server-picker#21]
I blocked all connections and left unblocked Amsterdam only due to having the lowest ping when connected to the Amsterdam Game server, and currently, I am connected to the Frankfurt Game server which is being routed through London. Both of these cities have been blocked in your program.

**Comment by FN-FAL113** [comment]
> I blocked all connections and left unblocked Amsterdam only due to having the lowest ping when connected to the Amsterdam Game server, and currently, I am connected to the Frankfurt Game server which is being routed through London. Both of these cities have been blocked in your program.

Please refer to FAQ in readme. Valve datagram service handles routing to nearest available server where other players are routed also.

**Comment by NewbieCPlusPlus** [comment]
So then your program makes no sense at all.

If you cannot force a gameserver, and you cannot force a routed server, what is the point of this program then? 

It looks like the CS2 in the end chooses game server as well as routed server just as it would if i didnt use this program.
