### ISSUE TITLE
Only one Indian server is on the list when there are two of them

### ISSUE THREAD

**Issue by NacasB** [FN-FAL113/cs2-server-picker#22]
There are two servers in India(Mumbai and Chennai) but there is only one "India" server, can you add another one please? I'm not sure if they are merged into one "India" but can you add both of them please? They are very different servers.

And also looks like Hong Kong servers are named "China" in the program, can you rename it to "Hong Kong" in the next update please? It is very confusing to me since I am korean who play on both china and hong kong servers. They are completely different servers thus Hong Kong server is not China server. They are seperated and the actual China server can be only played via Steamchina version. And the Hong Kong server is also called "Hong Kong" server on the steam and in game too. I think it will be better to say Hong Kong instead of China.

Thanks for the great program!

**Comment by FN-FAL113** [comment]
Yeah they are clustered or merged. I'll release an unclusteree one later, currently sick atm.

**Comment by NacasB** [comment]
Thank you so much! I hope you get better! Stay safe my friend - from korea

**Comment by FN-FAL113** [comment]
Just made a progress on this feature, I will send an unreleased build here later on for you to test out  :) if you are willing.
