### ISSUE TITLE
Server Data Fetch/Display Error

### ISSUE THREAD

**Issue by Diggeris** [FN-FAL113/cs2-server-picker#25]
Hello, 
when trying to open the application, a popup appears Server Data Fetch/Display Error. An error has occurred while retrieving or displaying server data

**Comment by FN-FAL113** [comment]
Have you tried using vpn

**Comment by FN-FAL113** [comment]
Tested it, facing same issue, will take a look.

**Comment by FN-FAL113** [comment]
Will push a fix in a moment. Thank you for making an entry in the issue tracker!
