### ISSUE TITLE
Latency aquring is too slow or not working sometimes

### ISSUE THREAD

**Issue by rainbowjose** [FN-FAL113/cs2-server-picker#27]
![mTnQjFk 2](https://github.com/FN-FAL113/cs2-server-picker/assets/6819554/0538b048-3dc6-471f-8453-9262ca2bd6db)

Subj. Without any conditions latency aquring still working bad.

**Comment by FN-FAL113** [comment]
Gonna see what I can do to improve it

**Comment by FN-FAL113** [comment]
New version released! Thank your contributing by reporting through issue tracker 😄.

**Comment by FN-FAL113** [comment]
@rainbowjose I wanna say thank you so much for the donation again, it really warms my heart 😭 and I hope you enjoy using the app!
