### ISSUE TITLE
A few enchancements that would make the app better

### ISSUE THREAD

**Issue by Ziya-Sharifli** [FN-FAL113/cs2-server-picker#30]
Hi. Thank you for making this piece of software. It has come in so handy and I'm finally free of Russians and slavs in general in my game.
I have a few feature requests that would be nice to see here:

1. **Theming**: A simple button to change from dark mode to light mode would be nice.
2. **Sorting**: A better sorting system would be nice, for example group regions together. NA stays at the top, EU second, AUS third and vice versa.
3. **Filters**: Although not very useful, it would make the program less cluttered. Adding an option to "always block this server" so you never see it on your list again and keeping the ones that you constantly block and unblock.
4. **Fun stuff**: Adding flags next to the server names would look nice. Like JFK would have the USA flag next to it and vice versa.
5. **Hide to system tray**: Make the program hide to system tray instead of taskbar and have an easy access to it from there. Right clicking the system tray icon could reveal some features with something easy like "enable and disable".
6. **Windows Startup**: Starting the software in the background when windows starts would be amazing to see so you don't have to click on it every time. you start your computer. It would basically be setup and forget.

Thank you for your work. I'm learning vb.net and will try to help with your project and send you a pull request on any of these that I might add myself and contribute. I'll also see if there is a way to support this on Linux.

**Comment by FN-FAL113** [comment]
Really happy you have benefitted from the app. Great list of features u have listed there. If I have the time in the future I'll take each feature into consideration. PR's are also welcome.
