### ISSUE TITLE
open position

### ISSUE THREAD

**Issue by Pandena** [FN-FAL113/cs2-server-picker#32]
Hello, are you still an active developer in cs? We would like to hire you to work on a p2p skin trading system for our platform

**Comment by FN-FAL113** [comment]
> Hello, are you still an active developer in cs? We would like to hire you to work on a p2p skin trading system for our platform

@Pandena 
Contact me at my personal email: 
orbetajeff@gmail.com

**Comment by Pandena** [comment]
done
