### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Tequinzyy** [FN-FAL113/cs2-server-picker#34]
Blocked Hong Kong and all china servers. After that i only get HongKong and haven't gotten a single Singapore since which is the 2nd closest. Firewall on or off no difference

**Comment by FN-FAL113** [comment]
https://github.com/FN-FAL113/cs2-server-picker?tab=readme-ov-file#faq

Please refer to FAQ 1

**Comment by FN-FAL113** [comment]
> Blocked Hong Kong and all china servers. After that i only get HongKong and haven't gotten a single Singapore since which is the 2nd closest. Firewall on or off no difference

do you have a screenshot of the server you are being connected, also try restarting your pc after blocking

**Comment by Tequinzyy** [comment]
Turning vpn on and then off again fixed my issue.

**Comment by FN-FAL113** [comment]
> Turning vpn on and then off again fixed my issue.

Nice, good to hear the server picker now works on your side!
