### ISSUE TITLE
India has 2 servers in Mumbai (bom and bom2) but it displays them together

### ISSUE THREAD

**Issue by updeshxp** [FN-FAL113/cs2-server-picker#35]
I would like to block bom2 as it is practically a dead server.

**Comment by FN-FAL113** [comment]
> I would like to block bom2 as it is practically a dead server.

did you try uncluster feature

**Comment by FN-FAL113** [comment]
Seems like they are merged into one, I might push an update later on, thank you for reporting.

**Comment by FN-FAL113** [comment]
resolved on latest version (v2.0.8), feedbacks are welcome.
