### ISSUE TITLE
Server Picker is not working for me

### ISSUE THREAD

**Issue by gabbar111999** [FN-FAL113/cs2-server-picker#37]
I guess previously,
My norton was blocking the app launch.
But now  when I have turned off the firewall,
The server picker is not working for me.

So basically, I am playing from UK with my Indian friends in Indian server.
Previously, I was getting 130-150ms ping.
But now its connecting to Indian server when I play with my friend it shows 380 ping as its getting routed through Amsterdam even when I am blocking Amsterdam.
![Untitled](https://github.com/FN-FAL113/cs2-server-picker/assets/159081068/56d4581d-e001-4675-8648-d5f646beaecd)
Attached is the picture.
Could you please help as I am fed up getting routed from Amsterdam

**Comment by FN-FAL113** [comment]
turn off av firewall and vpn if you have, then restart your pc.

**Comment by gabbar111999** [comment]
Hello,

Thanks for your reply.
I have norton av and I have turned off all the firewalls. Still its not working.
Could you please suggest?

**Comment by FN-FAL113** [comment]
> Hello,
> 
> Thanks for your reply. I have norton av and I have turned off all the firewalls. Still its not working. I have also tried uninstalling norton av and then turning off all the firewalls for windows defender, still not working. Could you please suggest?
> 
> The only need for me is to not getting routed through Amsterdam. Is there any way that I can connect via DIrect Route as the Direct route ping is 140ms, on the other had with Amsterdam, its comming as 380ms.
> 
> ![image](https://private-user-images.githubusercontent.com/159081068/302613414-001b4682-066f-48cb-8f93-46f01b3cefd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjY4NjAsIm5iZiI6MTcwNzIyNjU2MCwicGF0aCI6Ii8xNTkwODEwNjgvMzAyNjEzNDE0LTAwMWI0NjgyLTA2NmYtNDhjYi04ZjkzLTQ2ZjAxYjNjZWZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMzM2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWJjMTMyZGM5Yzg4MmViNGE2YzIwMzYyYzE5YTUzOGFhMGZiZDY4MjBlN2I3NzE5NGQxYWIyMDI4ZTEzOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZYBqBrHSnBu2wa7HDJzRwaCwEvoiy---EZIPMjBQTvU)

Please don't turn off windows defender firewall, this app relies on windows firewall which win defender manages also.

**Comment by FN-FAL113** [comment]
Closing this as stale, please commend back incase

**Comment by gabbar111999** [comment]
Hi,
I think its still for working for me.
Also, 
I am not able to block Amsterdam ( its comming routed through always)
