### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by shadept-GitHub** [FN-FAL113/cs2-server-picker#43]
i blocked everything but US servers so i dont queue up with a certain biomass from eastern europe and yet i still get servers in EU, my antivirus is not real time so it has no firewall protection btw

**Comment by FN-FAL113** [comment]
> i blocked everything but US servers so i dont queue up with a certain biomass from eastern europe and yet i still get servers in EU, my antivirus is not real time so it has no firewall protection btw

App requires windows firewall enabled be managed by windows defender and no third party antivirus.

**Comment by shadept-GitHub** [comment]
i figured it out, i had to start it before the game

**Comment by FN-FAL113** [comment]
> i figured it out, i had to start it before the game

Give the project a star if it helped you out :) nonetheless goodluck and have fun!

**Comment by shadept-GitHub** [comment]
np, gave it a star btw, finally i can play with NA people (even with a ping disadvantage)
