### ISSUE TITLE
Block didnt work

### ISSUE THREAD

**Issue by tw0f1sh** [FN-FAL113/cs2-server-picker#44]
I play active on helsinki right now, i block all localtions via this app and i am still able to play, i double checked: my firewall is active. i get into advanced option and i see ther is an outbound entry for each server in my firewall but still, i can play...

how's that possible?

edit: now i know why... the game server is at location X and you getting routed to that location via your blocks, so that makes this tool useless bec you just play on high ping servers but with a higher pinged tunnel to it...

**Comment by tw0f1sh** [comment]
now i know why... the game server is at location X and you getting routed to that location via your blocks, so that makes this tool useless bec you just play on high ping servers but with a higher ping tunnel to it...

**Comment by FN-FAL113** [comment]
Please refer to FAQ #2. Try also restarting your pc or game else its location factor.

**Comment by FN-FAL113** [comment]
Blocking everything is not recommended why even do that, it limits the games ability to find proper servers based on where players are actively searching.
