### ISSUE TITLE
not blocking servers.

### ISSUE THREAD

**Issue by labaland** [FN-FAL113/cs2-server-picker#45]
Im blocking all server but not sweden and finland, stil get other servers.
run the program as admin, and nothing added to hostfile, but i guess it should be like that :P

**Comment by FN-FAL113** [comment]
Check #43 and #34 else it might be your location.

**Comment by FN-FAL113** [comment]
Also app utilizes windows firewall not host file as it is for domain ip mapping

**Comment by FN-FAL113** [comment]
You may keep commenting here even when closed. Duplicate issue.

**Comment by labaland** [comment]
> You may keep commenting here even when closed. Duplicate issue.

I use windows firewall and antivitus that is in windows 11, do i have have to open the blocker everytime before i start cs? i guess i have to try that :P

**Comment by FN-FAL113** [comment]
> > You may keep commenting here even when closed. Duplicate issue.
> 
> I use windows firewall and antivitus that is in windows 11, do i have have to open the blocker everytime before i start cs? i guess i have to try that :P

You have to test and verify yourself if you are being connected properly to any of your unblocked servers using steam overlay which shows the server similar to what these guys from youtube did:
[video #1](https://www.youtube.com/watch?v=A2BPAp4QrUA&t=1s)
[video #2](https://www.youtube.com/watch?v=54aqpRMcyPo&t=1s)

 If its not working on your side, I'm sorry I cannot help you any further it might be your location.

**Comment by labaland** [comment]
oh, maybe it is beacus i get routed thru a swedish server to another?
Whats happends if a friend is party leader and searches for a game? then it can still join a blocked server i guess? :) 

Thanks!

**Comment by FN-FAL113** [comment]
> oh, maybe it is beacus i get routed thru a swedish server to another? Whats happends if a friend is party leader and searches for a game? then it can still join a blocked server i guess? :)
> 
> Thanks!

Maybe, you can view it from the steam overlay
