### ISSUE TITLE
Re-routing 100% of the time, thus making the app effectively useless

### ISSUE THREAD

**Issue by osctorand** [FN-FAL113/cs2-server-picker#46]
I live in Sweden. When using the app to block certain servers the game re-routes me to the blocked servers 100% of the time, and makes the app completely useless. This is easily seen on the connection information on the top right of the steam overlay. I am not sure if this is even fixable considering the information in the readme, but this is still an issue nonetheless.

**Comment by FN-FAL113** [comment]
I'm sorry to hear it doesn't work out for you, make sure there are no vpn or other antivirus software installed to let windows defender manag3 the firewall. You may also try blocking servers while the game ia closed then doing a pc restart else it might be your location that steam rerouted you.
