### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by St0RM53** [FN-FAL113/cs2-server-picker#47]
- When creating a preset you need to double click check boxes to select; only one click should be needed
- Allow to edit preset
- Button to invert selection
- Button to block all servers except the ones in a preset

Kind regards

**Comment by FN-FAL113** [comment]
Hello, thanks for the great input. I'll take a look at some of these. The checkbox might have a default behavior of double click select but I'll check out if it can be overridden.

**Comment by FN-FAL113** [comment]
Also forgot to mention, give the app an star if you benefir from it 😄. Have a great one.
