### ISSUE TITLE
CS2 routes me to China -> use CS2ServerPicker to block it -> now I have no Server available

### ISSUE THREAD

**Issue by amarinhooo23** [FN-FAL113/cs2-server-picker#49]
Good Morning everyone,

Since i left my Parents house I have this issue with my new internet that no steam game works. I live in Germany and it routes me to China.
 Even with this CS2ServerPicker it does not work. Maybe somebody knows what I can do because my ISP has no clue what they can do because they say that they have nothing blocked there.
Only thing that works is VPN routing me to Frankfurt or Nuremberg
 
 
![CS2](https://github.com/FN-FAL113/cs2-server-picker/assets/103938476/eed69133-6b18-4a31-90a2-58d002811556)
Issue without using VPN and CS2ServerPicker
![WhatsApp Image 2024-03-31 at 10 59 26 AM](https://github.com/FN-FAL113/cs2-server-picker/assets/103938476/70a63110-b632-48a8-acb5-b7efc8714e08)
![WhatsApp Image 2024-03-31 at 10 59 26 AM(2)](https://github.com/FN-FAL113/cs2-server-picker/assets/103938476/bf0fcaf6-8dbe-4966-ab51-dbd4f50ecb2c)
Issue with CS2ServerPicker
![WhatsApp Image 2024-03-31 at 10 59 26 AM(1)](https://github.com/FN-FAL113/cs2-server-picker/assets/103938476/878f3f2c-c719-44fe-baa0-8b3e86eb743e)
No Server available

**Comment by FN-FAL113** [comment]
Hello amarinhoo, have you tried restarting your pc after blocking servers, make sure to not block most of the server for proper routing. If nothing have worked these are the procedures I like to suggest.
1. Remove any third party antivirus and let windows defender manage the firewall (make sure firewall is also enabled)
2. Turn off any VPN
3. Reinstall the game
4. Reformatting your pc (only if you want)
5. Might be an ISP problem, try talking to them about configuring your network or try switching routers (take this as a grain of salt)

**Comment by amarinhooo23** [comment]
Hey, 

I have tried a lot of things actually and everything you said except the 5th. I contacted them

![grafik](https://github.com/FN-FAL113/cs2-server-picker/assets/103938476/93521150-42a1-4f30-ba6b-d29e2112157d)

Does this look ok to you?

**Comment by FN-FAL113** [comment]
Looking at the tracert, It's looking fine it only took 9 hops to reach the ip address but I don't think its enough to determine your network issues. May I also suggest using google dns or opendns in your dns settings ([tutorial](https://www.youtube.com/watch?v=u05mEXGc8uQ)).

**Comment by FN-FAL113** [comment]
What bothers me is that when u blocked china in the app, you cannot find any servers anymore. I might be thinking that your router is somehow doing something behind the scene through its configuration or it might be a chinese router. Really would like to suggest testing with a different router.

**Comment by FN-FAL113** [comment]
As a last resort if the ISP is not able to fix the problem even with changing routers, I'd try changing to different ISP.

**Comment by FN-FAL113** [comment]
I will be closing this for now, you may keep commenting here as u wish. I'll still be active incase.

**Comment by amarinhooo23** [comment]
> Looking at the tracert, It's looking fine it only took 9 hops to reach the ip address but I don't think its enough to determine your network issues. May I also suggest using google dns or opendns in your dns settings ([tutorial](https://www.youtube.com/watch?v=u05mEXGc8uQ)).

I can try the other 2 DNS because I only did the google DNS, i keep u updated.

**Comment by amarinhooo23** [comment]
> As a last resort if the ISP is not able to fix the problem even with changing routers, I'd try changing to different ISP.

I would love to change it but there is currently only one ISP in my street that can give me internet so I am kinda doomed until something changes here

**Comment by amarinhooo23** [comment]
> What bothers me is that when u blocked china in the app, you cannot find any servers anymore. I might be thinking that your router is somehow doing something behind the scene through its configuration that it limits you to china or it might be a chinese router. Really would like to suggest testing with a different router.

Nothing is configured there except the internet provider has put their username and password so they have the connection to it or something idk... Its a german provider so there is nothing that relates to China..

**Comment by amarinhooo23** [comment]
> Looking at the tracert, It's looking fine it only took 9 hops to reach the ip address but I don't think its enough to determine your network issues. May I also suggest using google dns or opendns in your dns settings ([tutorial](https://www.youtube.com/watch?v=u05mEXGc8uQ)).

Tried it out, did not work :(

**Comment by FN-FAL113** [comment]
Changing ISP as a last resort. I have nothing more to suggest unfortunately...
