### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by T1Founder** [FN-FAL113/cs2-server-picker#52]
I ran the exe as admin and run it, blocked the servers i wanted to block then opened cs2  and loaded up a premier game. it was in the server I blocked...

**Comment by T1Founder** [comment]
nevermind i  fixed. just ran as admin and tried it again after restarting pc and it works now.

**Comment by FN-FAL113** [comment]
> nevermind i fixed. just ran as admin and tried it again after restarting pc and it works now.

Great it works on your rig, have fun
