### ISSUE TITLE
ping spike issue

### ISSUE THREAD

**Issue by ketho2517** [FN-FAL113/cs2-server-picker#53]
hi, first of all thanks ALOT for this nifty software to let me play on any region i want, i've been using it since the day you posted it here, i usually play on China servers but recenlt my ping just spikes from 200-600ms (before it was constantly on 100ms) which was fine, i usually just redownload it and run it and it works again for most of the time, but now it just spikes every game, is the problem from my ISP or is it fixable? thanks a lot again

**Comment by FN-FAL113** [comment]
Hello ketho, first of all thanks for using the app. Regarding your issue, I suspect this might be an issue with your ISP. I can only suggest things that might not work which are uninstalling any third party antivirus and let windows defender manage the firewall, turn off vpn and resetting your network router if you have access to it.
