### ISSUE TITLE
Russia is missing

### ISSUE THREAD

**Issue by OZZlE** [FN-FAL113/cs2-server-picker#57]
I am located in Sweden, I just installed this app but Russia is not in the list, the only one I wanted to block :P

Every time I play there are only russians, often using Aim bots

**Comment by FN-FAL113** [comment]
> I am located in Sweden, I just installed this app but Russia is not in the list, the only one I wanted to block :P
> 
> Every time I play there are only russians, often using Aim bots

Hello,

What you see in the server list is what valve provides, russia has no dedicated servers. Hope this clarifies your query!
