### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Mrbobe72** [FN-FAL113/cs2-server-picker#58]
![Без имени](https://github.com/user-attachments/assets/0d8b3c2e-9e75-4fc0-91dd-56ed62657a53)

**Comment by FN-FAL113** [comment]
I'll test it out later.

**Comment by FN-FAL113** [comment]
> ![Без имени](https://private-user-images.githubusercontent.com/178044053/356835213-0d8b3c2e-9e75-4fc0-91dd-56ed62657a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTU2NDcsIm5iZiI6MTcyMzM1NTM0NywicGF0aCI6Ii8xNzgwNDQwNTMvMzU2ODM1MjEzLTBkOGIzYzJlLTllNzUtNGZjMC05MWRkLTU2ZWQ2MjY1N2E1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwNTQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2RlOTMzOWI5M2RmODliNzZkY2VjMDcxZWM3MTRiZWQxZjkwMTVlNTM3MzljMjY4YTdjNmJkNzk3ODUzZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gIM_SJjLnaYbR9nJPypsjslVFi34VqJQZXRoaHQ2w2A)

Its working fine after testing, can you show app info so I can see what version you have. May I also suggest having no other antivirus and let windows defender manage the firewall
![image](https://github.com/user-attachments/assets/9115394e-d335-4a4c-9289-8825711790bb)

**Comment by Mrbobe72** [comment]
![Безымянный](https://github.com/user-attachments/assets/9fb8cf09-9a11-4be9-af18-45a2436fb62e)

no other antivirus is used windows Defender manages the firewall.

**Comment by Mrbobe72** [comment]
windows swears at the program's malfunction, as if it does not understand which system it should work under. I have windows 10

**Comment by FN-FAL113** [comment]
> windows swears at the program's malfunction, as if it does not understand which system it should work under. I have windows 10

Can you send a screenshot of your windows firewall

**Comment by FN-FAL113** [comment]
![image](https://github.com/user-attachments/assets/4ddac6bf-2fd7-47c4-b2cc-c57800af43c1)

**Comment by FN-FAL113** [comment]
> windows swears at the program's malfunction, as if it does not understand which system it should work under. I have windows 10

Also run the app as administrator if it has not been executed that way.

**Comment by FN-FAL113** [comment]
Closing this for now, feel free to comment back.
