### ISSUE TITLE
The problem with unblocking the region

### ISSUE THREAD

**Issue by krst1k** [FN-FAL113/cs2-server-picker#59]
I'm blocking all regions, I want to unblock China, and it gives me an error. What to do, help.
![Скриншот 11-08-2024 193847](https://github.com/user-attachments/assets/228ddc2d-2550-48ad-9d24-34a4a9e4d876)

**Comment by FN-FAL113** [comment]
is the error displayed in russian if so can u translate it to english please?

**Comment by FN-FAL113** [comment]
Closing as stale, but worth noting since I haven't tested the app on different languages where issues might be related to parsing text.
