### ISSUE TITLE
New Server: United Kingdom

### ISSUE THREAD

**Issue by M0R155** [FN-FAL113/cs2-server-picker#62]
Hey!

First of all thanks so much for this tool, it allows us to play with our far-away-friend in the middle so we can all have OK-ish-ping.

Volvo seems to have added UK as another node, we are getting relayed from India/UAE over to UK with 510 ping :'D

Please add it when you find the time and thanks again

Moriss

**Comment by FN-FAL113** [comment]
Hello MOR155,

Thank you for the feedback I really appreciate them. Regarding UK, the servers you see from the app are the ones available and provided by valve. These servers are fetched every time you execute the app which means if valve updates the server list the app will also source the changes.
