### ISSUE TITLE
Option to disable version checker on startup

### ISSUE THREAD

**Issue by alexitx** [FN-FAL113/cs2-server-picker#63]
Since I read changelogs and update all of my software manually, I always disable automatic update checks on startup.

Those who might be using slightly older version intentionally or planning to update soon, just not immediately, should be able to disable the prompt and avoid making repeated requests to GitHub's API every time the app is launched making the update check a nice quality-of-life feature that is optional and not forced by default.

**Comment by FN-FAL113** [comment]
Hello alexitx, I'll try making this check optional, thanks for reaching this out.

**Comment by FN-FAL113** [comment]
![image](https://github.com/user-attachments/assets/9d517d13-883c-41db-917f-f6cd0462ab40)

Should be released in a moment

**Comment by FN-FAL113** [comment]
Released on v2.2.1
Have fun!
