### ISSUE TITLE
cs picker error

### ISSUE THREAD

**Issue by valyshhhaa** [FN-FAL113/cs2-server-picker#65]
![image](https://github.com/user-attachments/assets/2e81804e-39d1-4e0a-b76b-45064a12a573)

**Comment by FN-FAL113** [comment]
> ![image](https://private-user-images.githubusercontent.com/151287499/366257909-2e81804e-39d1-4e0a-b76b-45064a12a573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMTU4NzEsIm5iZiI6MTcyNjAxNTU3MSwicGF0aCI6Ii8xNTEyODc0OTkvMzY2MjU3OTA5LTJlODE4MDRlLTM5ZDEtNGUwYS1iNzZiLTQ1MDY0YTEyYTU3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwMDQ2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWM2NDg5ZTlhYjhlODI0YzRlYjc5MTI4ZjNkODkxMWQ3M2VmZDUzMTYwZTdmZjZkZWU3YTJmMTIyZmI5MTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7gYzi6FVeDpUHkkoHd7pYhUew38v3HLESKZT5NLlqG0)

Can you translate the error to english here?

**Comment by NoPlagiarism** [comment]
> Can you translate the error to english here?

Untranslatable gibberish. Wrong encoding, LOL

**Comment by FN-FAL113** [comment]
> > Can you translate the error to english here?
> 
> Untranslatable gibberish. Wrong encoding, LOL

Windows is weird, I wonder if I could replicate this on a different language pack.

**Comment by FN-FAL113** [comment]
@valyshhhaa Please try out version 2.2.3 and upload the error file located in the base directory when an error is encounted on this issue tracker.
