### ISSUE TITLE
programm error "while blocking/unblocking..."

### ISSUE THREAD

**Issue by GoFormerSetup** [FN-FAL113/cs2-server-picker#69]
I'm launching app as administrate. Cannot block any server it seems program not working at all. Tried to block/unblock firewall same errors.
![image](https://github.com/user-attachments/assets/7661108e-f8d6-4aec-a9bb-fed02c35d52d)
![image](https://github.com/user-attachments/assets/60c8d616-f352-40ac-9642-b2e19f28f7c3)
![image](https://github.com/user-attachments/assets/9443cc9d-a261-4d0c-ab86-91666e2cdb7e)

**Comment by GoFormerSetup** [comment]
![image](https://github.com/user-attachments/assets/81f4c628-ece1-49b9-803f-eab2e9c92bcb)
I havn't any runnig antiviruses or vpn programs. Windows defender is off.

**Comment by FN-FAL113** [comment]
> ![image](https://private-user-images.githubusercontent.com/183331409/371929238-81f4c628-ece1-49b9-803f-eab2e9c92bcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjY3OTMsIm5iZiI6MTcyNzY2NjQ5MywicGF0aCI6Ii8xODMzMzE0MDkvMzcxOTI5MjM4LTgxZjRjNjI4LWVjZTEtNDliOS04MDNmLWVhYjJlOWM5MmJjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMzIxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWU2ZjAxOTZjNGU2MmUxMTkzZTE3YzU2ZmE4N2RkN2ZmYjE4ZWM3MThhNTMyZmU4ZjViNTM3NzJlMTVjYjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ueerFMyP2j6I1TSZC4JnilUK7-7PsPSKNPX_aZHVcBE) I havn't any runnig antiviruses or vpn programs. Windows defender is off.

Windows defender should be enabled.

**Comment by FN-FAL113** [comment]
I haven't tested the app on different language pack, I've seen other people had issues with non-English systems

**Comment by FN-FAL113** [comment]
@GoFormerSetup  Please try out version 2.2.3 and upload the error file located in the base directory when an error is encountered on this issue tracker.

I am not able to reproduce this error on a guest virtual box host with Russian display language pack.

**Comment by FN-FAL113** [comment]
Might also work taking a look the suggested resources mentioned in a recent issue report relating to firewall/system configurations. Thanks.
#72
