### ISSUE TITLE
cant choose australian server

### ISSUE THREAD

**Issue by lou-ctrl** [FN-FAL113/cs2-server-picker#71]
![image](https://github.com/user-attachments/assets/1970660a-fc34-4590-9716-be34718e8fbd)
plz help im from aus but havent been playing on oz servers in ages

**Comment by FN-FAL113** [comment]
You already blocked the servers, try playing in-game

**Comment by FN-FAL113** [comment]
You can double click the server to ping it again, if you have third party antivirus please uninstall them or any vpn.

**Comment by lou-ctrl** [comment]
im trying to play aus servers
ive uninstalled all vpns and anti virus software
![image](https://github.com/user-attachments/assets/f8ce5a49-f6ed-470c-b028-b7b94c6a1496)
results are still the same

**Comment by lou-ctrl** [comment]
![image](https://github.com/user-attachments/assets/ab3d8628-a037-4e54-bfc9-18d31e32b834)

**Comment by FN-FAL113** [comment]
> im trying to play aus servers ive uninstalled all vpns and anti virus software ![image](https://private-user-images.githubusercontent.com/183758212/373609723-f8ce5a49-f6ed-470c-b028-b7b94c6a1496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDE3NjUsIm5iZiI6MTcyODA0MTQ2NSwicGF0aCI6Ii8xODM3NTgyMTIvMzczNjA5NzIzLWY4Y2U1YTQ5LWY2ZWQtNDcwYy1iMDI4LWI3Yjk0YzZhMTQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxMTMxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTUwZWM3MGYyNjE1YzBhZDMyNTRjYjVkNTc3YjYxZGM1MGQ0MDgwMDhhZmQ1NGRjODRjZmViMzI2ZWViZTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-dGGTFEpur_k98viWdcx0YViVRhGfgUYilxD9vBTVXU) results are still the same

This might be an issue with your ISP (bad routing, etc). I highly suggest contacting them, most servers time out after doing the previous suggested steps.

**Comment by lou-ctrl** [comment]
i have used this before plenty of times being able to play from singapore to australia. even if i uninstall it and restart pc, it still connects to singapore servers

**Comment by lou-ctrl** [comment]
![20241004212715_1](https://github.com/user-attachments/assets/73ae37ba-9e14-4dd1-9594-977e4b4a0341)
australia usually would be shown on that list, its still being blocked.

**Comment by FN-FAL113** [comment]
> ![20241004212715_1](https://private-user-images.githubusercontent.com/183758212/373629438-73ae37ba-9e14-4dd1-9594-977e4b4a0341.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDYzNTgsIm5iZiI6MTcyODA0NjA1OCwicGF0aCI6Ii8xODM3NTgyMTIvMzczNjI5NDM4LTczYWUzN2JhLTllMTQtNGRkMS05NTk0LTk3N2U0YjRhMDM0MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxMjQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWM5NmNjMmQ4NTk0Zjc4Y2NiZWY4YjQyZTQ1MWMzMjA0NmU5ZmQ3MDY4OTQzODhkODRlNDhhNTkyYjViYzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PRkJRYe9-andpuaI6SeZdQcWfCkS9Jua3UsSxfppikM) australia usually would be shown on that list, its still being blocked.

That list is hardcoded and it might use a different server relay if you block most of the servers from the region/country.

**Comment by FN-FAL113** [comment]
> i have used this before plenty of times, being able to play from singapore to australia. even if i uninstall it and restart pc, it still connects to singapore servers

This app only adds firewall entries, for me its quite obvious that your connection is having some issues pinging other servers which might be related to your **Internet Service Provider** or how your system configuration is handled or misconfigured.

**Comment by lou-ctrl** [comment]
was reading over internet settings and came across 'firewall' earlier. im no i.t nor even experienced in technology. in windows security there is a firewall and network protection. when you mentioned it added firewall entries, i then restored firewalls to default. i can now play on australian servers  :) thanks for the help

**Comment by lou-ctrl** [comment]
after switching steam accounts however this has popped up.
![image](https://github.com/user-attachments/assets/6446ed8f-af89-4fbc-927b-87a607c40152)
would i have to let it access private networks?

**Comment by FN-FAL113** [comment]
> was reading over internet settings and came across 'firewall' earlier. im no i.t nor even experienced in technology. in windows security there is a firewall and network protection. when you mentioned it added firewall entries, i then restored firewalls to default. i can now play on australian servers :) thanks for the help

Awesome, have fun! 😄
