### ISSUE TITLE
What does this mean

### ISSUE THREAD

**Issue by Oxbacod** [FN-FAL113/cs2-server-picker#72]
An error has occurred while blocking/unblocking selected server!

An unrecoverable Windows Defender Firewall error (0x2) occurred

**Comment by FN-FAL113** [comment]
> An error has occurred while blocking/unblocking selected server!
> 
> An unrecoverable Windows Defender Firewall error (0x2) occurred

Please upload the error text file here.

**Comment by Oxbacod** [comment]
Got it to work, just required a scan and a windows update at the end of the day i guess, thanks anyways :)

**Comment by FN-FAL113** [comment]
> Got it to work, just required a scan and a windows update at the end of the day i guess, thanks anyways :)

Great to hear its now sorted! Have a great day and have fun!
