### ISSUE TITLE
Error When Block Server

### ISSUE THREAD

**Issue by nlebo** [FN-FAL113/cs2-server-picker#73]
**Describe the bug**

**To Reproduce (Important)**
2. Click on 'Block All or BlockSelected'

**Screenshots**
![image](https://github.com/user-attachments/assets/781ec213-48ed-4ffc-9fb9-831bf74fcd29)

**Error File (Required)**
Upload the error file located in the application's executable directory.
[error_1728813636.txt](https://github.com/user-attachments/files/17355141/error_1728813636.txt)

**Comment by FN-FAL113** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce (Important)** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on 'Block All or BlockSelected'
> 3. Scroll down to '....'
> 4. See error
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://private-user-images.githubusercontent.com/61404266/376025102-781ec213-48ed-4ffc-9fb9-831bf74fcd29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTQzNTksIm5iZiI6MTcyODgxNDA1OSwicGF0aCI6Ii82MTQwNDI2Ni8zNzYwMjUxMDItNzgxZWMyMTMtNDhlZC00ZmZjLTlmYjktODMxYmY3NGZjZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEwMDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMmRhNDNjZmQ0YjE5MmRhMGVmYmI2MGNlZTJlZjMzNDM1MTk2ODFkOGZiNTFiYjY2OTk2NGEyYjIxNzNlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tNy9S7aorKUVSBBHz01ChkyfcpNaSznh5YBSLYkIwf0)
> 
> **Error File (Required)** Upload the error file located in the application's executable directory. [error_1728813636.txt](https://github.com/user-attachments/files/17355141/error_1728813636.txt)

Some steps I can recommend:
- Reset windows firewall and make sure its enabled
- uninstall any third party antivirus and vpn's
- let windows defender manage the firewall.

**Comment by FN-FAL113** [comment]
New update has been released. You can reset the firewall from there or check its status.

**Comment by nlebo** [comment]
@FN-FAL113  Still error... help me

**Comment by FN-FAL113** [comment]
> @FN-FAL113 Still error... help me

Send error file again here

**Comment by nlebo** [comment]
[error_1728995092.txt](https://github.com/user-attachments/files/17377956/error_1728995092.txt)
here error log

**Comment by FN-FAL113** [comment]
> [error_1728995092.txt](https://github.com/user-attachments/files/17377956/error_1728995092.txt) here error log

did your run the app as administrator? right click exe > run as administrator.

**Comment by nlebo** [comment]
yes i did

**Comment by FN-FAL113** [comment]
> yes i did

Your system doesn't seem to have access to the "netsh" command which might imply your system is misconfigured, missing system files or environment variables.

**Comment by FN-FAL113** [comment]
I suggest you take a look at your system setup. Reinstalling windows might help but will cause you some time at your dispense else you have to troubleshoot your pc for the "netsh" command to work properly.
